import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {Path, Svg} from 'react-native-svg';
import global from '../../assets/global.jsx';

export default function Privacy({navigation}) {
  const {navigate} = navigation;

  return (
    <View style={global.container}>
      <View style={global.topBar}>
        <View style={global.screenInfo}>
          <TouchableOpacity
            onPress={() => {
              navigate('Home');
            }}
            style={styles.backBtn}
            activeOpacity={0.8}>
            <Svg
              width={32}
              height={32}
              viewBox="0 0 24 24"
              fill={'white'}
              xmlns="http://www.w3.org/2000/svg">
              <Path d="m9.474 5.209s-4.501 4.505-6.254 6.259c-.147.146-.22.338-.22.53s.073.384.22.53c1.752 1.754 6.252 6.257 6.252 6.257.145.145.336.217.527.217.191-.001.383-.074.53-.221.293-.293.294-.766.004-1.057l-4.976-4.976h14.692c.414 0 .75-.336.75-.75s-.336-.75-.75-.75h-14.692l4.978-4.979c.289-.289.287-.761-.006-1.054-.147-.147-.339-.221-.53-.221-.191-.001-.38.071-.525.215z" />
            </Svg>
          </TouchableOpacity>
          <View style={global.titleArea}>
            <Text style={{...global.title, marginLeft: 12}}>Privacidade</Text>
          </View>
        </View>
      </View>
      <ScrollView style={styles.privacyArea}>
        <Text style={styles.privacyText}>
          Privacy Policy{'\n'}
          Last updated: December 17, 2022{'\n'}
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.{'\n'}
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the TermsFeed Privacy Policy Generator.{'\n'}
          Interpretation and Definitions{'\n'}
          Interpretation{'\n'}
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.{'\n'}
          Definitions{'\n'}
          For the purposes of this Privacy Policy:{'\n'}
          Account means a unique account created for You to access our Service
          or parts of our Service.{'\n'}
          Affiliate means an entity that controls, is controlled by or is under
          common control with a party, where "control" means ownership of 50% or
          more of the shares, equity interest or other securities entitled to
          vote for election of directors or other managing authority.{'\n'}
          Application refers to GECOM, the software program provided by the
          Company.{'\n'}
          Company (referred to as either "the Company", "We", "Us" or "Our" in
          this Agreement) refers to GECOM.{'\n'}
          Country refers to: Brazil{'\n'}
          Device means any device that can access the Service such as a
          computer, a cellphone or a digital tablet.{'\n'}
          Personal Data is any information that relates to an identified or
          identifiable individual.{'\n'}
          Service refers to the Application.{'\n'}
          Service Provider means any natural or legal person who processes the
          data on behalf of the Company. It refers to third-party companies or
          individuals employed by the Company to facilitate the Service, to
          provide the Service on behalf of the Company, to perform services
          related to the Service or to assist the Company in analyzing how the
          Service is used.{'\n'}
          Third-party Social Media Service refers to any website or any social
          network website through which a User can log in or create an account
          to use the Service.{'\n'}
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).{'\n'}
          You means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable.{'\n'}
          Collecting and Using Your Personal Data{'\n'}
          Types of Data Collected{'\n'}
          Personal Data{'\n'}
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:{'\n'}
          Email address{'\n'}
          First name and last name{'\n'}
          Phone number{'\n'}
          Address, State, Province, ZIP/Postal code, City{'\n'}
          Usage Data{'\n'}
          Usage Data{'\n'}
          Usage Data is collected automatically when using the Service.{'\n'}
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.{'\n'}
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.{'\n'}
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.{'\n'}
          Information from Third-Party Social Media Services{'\n'}
          The Company allows You to create an account and log in to use the
          Service through the following Third-party Social Media Services:{'\n'}
          Google{'\n'}
          Facebook{'\n'}
          Twitter{'\n'}
          LinkedIn{'\n'}
          If You decide to register through or otherwise grant us access to a
          Third-Party Social Media Service, We may collect Personal data that is
          already associated with Your Third-Party Social Media Service's
          account, such as Your name, Your email address, Your activities or
          Your contact list associated with that account.{'\n'}
          You may also have the option of sharing additional information with
          the Company through Your Third-Party Social Media Service's account.
          If You choose to provide such information and Personal Data, during
          registration or otherwise, You are giving the Company permission to
          use, share, and store it in a manner consistent with this Privacy
          Policy.{'\n'}
          Information Collected while Using the Application{'\n'}
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:{'\n'}
          Information regarding your location{'\n'}
          Pictures and other information from your Device's camera and photo
          library{'\n'}
          We use this information to provide features of Our Service, to improve
          and customize Our Service. The information may be uploaded to the
          Company's servers and/or a Service Provider's server or it may be
          simply stored on Your device.{'\n'}
          You can enable or disable access to this information at any time,
          through Your Device settings.{'\n'}
          Use of Your Personal Data{'\n'}
          The Company may use Personal Data for the following purposes:{'\n'}
          To provide and maintain our Service, including to monitor the usage of
          our Service.{'\n'}
          To manage Your Account: to manage Your registration as a user of the
          Service. The Personal Data You provide can give You access to
          different functionalities of the Service that are available to You as
          a registered user.{'\n'}
          For the performance of a contract: the development, compliance and
          undertaking of the purchase contract for the products, items or
          services You have purchased or of any other contract with Us through
          the Service.{'\n'}
          To contact You: To contact You by email, telephone calls, SMS, or
          other equivalent forms of electronic communication, such as a mobile
          application's push notifications regarding updates or informative
          communications related to the functionalities, products or contracted
          services, including the security updates, when necessary or reasonable
          for their implementation.{'\n'}
          To provide You with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless You
          have opted not to receive such information.{'\n'}
          To manage Your requests: To attend and manage Your requests to Us.
          {'\n'}
          For business transfers: We may use Your information to evaluate or
          conduct a merger, divestiture, restructuring, reorganization,
          dissolution, or other sale or transfer of some or all of Our assets,
          whether as a going concern or as part of bankruptcy, liquidation, or
          similar proceeding, in which Personal Data held by Us about our
          Service users is among the assets transferred.{'\n'}
          For other purposes: We may use Your information for other purposes,
          such as data analysis, identifying usage trends, determining the
          effectiveness of our promotional campaigns and to evaluate and improve
          our Service, products, services, marketing and your experience.{'\n'}
          We may share Your personal information in the following situations:
          {'\n'}
          With Service Providers: We may share Your personal information with
          Service Providers to monitor and analyze the use of our Service, to
          contact You.{'\n'}
          For business transfers: We may share or transfer Your personal
          information in connection with, or during negotiations of, any merger,
          sale of Company assets, financing, or acquisition of all or a portion
          of Our business to another company.{'\n'}
          With Affiliates: We may share Your information with Our affiliates, in
          which case we will require those affiliates to honor this Privacy
          Policy. Affiliates include Our parent company and any other
          subsidiaries, joint venture partners or other companies that We
          control or that are under common control with Us.{'\n'}
          With business partners: We may share Your information with Our
          business partners to offer You certain products, services or
          promotions.{'\n'}
          With other users: when You share personal information or otherwise
          interact in the public areas with other users, such information may be
          viewed by all users and may be publicly distributed outside. If You
          interact with other users or register through a Third-Party Social
          Media Service, Your contacts on the Third-Party Social Media Service
          may see Your name, profile, pictures and description of Your activity.
          Similarly, other users will be able to view descriptions of Your
          activity, communicate with You and view Your profile.{'\n'}
          With Your consent: We may disclose Your personal information for any
          other purpose with Your consent.{'\n'}
          Retention of Your Personal Data{'\n'}
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.{'\n'}
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.{'\n'}
          Transfer of Your Personal Data{'\n'}
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the parties
          involved in the processing are located. It means that this information
          may be transferred to — and maintained on — computers located outside
          of Your state, province, country or other governmental jurisdiction
          where the data protection laws may differ than those from Your
          jurisdiction.{'\n'}
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.{'\n'}
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
          {'\n'}
          Delete Your Personal Data{'\n'}
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.{'\n'}
          Our Service may give You the ability to delete certain information
          about You from within the Service.{'\n'}
          You may update, amend, or delete Your information at any time by
          signing in to Your Account, if you have one, and visiting the account
          settings section that allows you to manage Your personal information.
          You may also contact Us to request access to, correct, or delete any
          personal information that You have provided to Us.{'\n'}
          Please note, however, that We may need to retain certain information
          when we have a legal obligation or lawful basis to do so.{'\n'}
          Disclosure of Your Personal Data{'\n'}
          Business Transactions{'\n'}
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.{'\n'}
          Law enforcement{'\n'}
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
          {'\n'}
          Other legal requirements{'\n'}
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:{'\n'}
          Comply with a legal obligation{'\n'}
          Protect and defend the rights or property of the Company{'\n'}
          Prevent or investigate possible wrongdoing in connection with the
          Service{'\n'}
          Protect the personal safety of Users of the Service or the public
          {'\n'}
          Protect against legal liability{'\n'}
          Security of Your Personal Data{'\n'}
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.{'\n'}
          Children's Privacy{'\n'}
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.{'\n'}
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent's consent before We collect and use that
          information.{'\n'}
          Links to Other Websites Our Service may contain links to other
          websites that are not operated by Us. If You click on a third party
          link, You will be directed to that third party's site. We strongly
          advise You to review the Privacy Policy of every site You visit.{'\n'}
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
          {'\n'}
          Changes to this Privacy Policy{'\n'}
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.{'\n'}
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the "Last
          updated" date at the top of this Privacy Policy.{'\n'}
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.{'\n'}
          Contact Us{'\n'}
          If you have any questions about this Privacy Policy, You can contact
          us:{'\n'}
          By email: support@quarkzplace.one{'\n'}
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  privacyArea: {
    padding: 12,
    backgroundColor: '#1e1e1e',
    marginBottom: 120,
    borderRadius: 15,
  },
  privacyText: {
    color: 'white',
    fontFamily: 'ClashGrotesk-Regular',
  },
});
